apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- test-pods_namespace.yaml
- test-pods_pod-disruption-budget.yaml
- cpu-limit-range_limitrange.yaml
- mem-limit-range_limitrange.yaml
- dind-docker-config_configmap.yaml
- buildkit-config_configmap.yaml
- buildctl-testbuild-script_configmap.yaml
- prow-test-admin_role.yaml
