presubmits:
  gardener/gardener:
  - name: pull-gardener-integration-release
    cluster: gardener-prow-build
    always_run: true
    # Run on release branches / adapt this setting and create a new job in case of incompatible changes in tests or go version between the releases
    branches:
    - release-v\d+.\d+
    skip_branches:
    - release-v1.([1-3][0-9]|4[0-6])
    decorate: true
    decoration_config:
      timeout: 20m
      grace_period: 10m
    annotations:
      description: Runs integration tests for gardener releases in pull requests
    spec:
      containers:
      - name: test-integration
        image: eu.gcr.io/gardener-project/ci-infra/golang-test:v20220517-f80c2bf-1.18
        command:
        - make
        args:
        - test-integration
        resources:
          limits:
            memory: 16Gi
          requests:
            cpu: 4
            memory: 8Gi
postsubmits:
  gardener/gardener:
  - name: post-gardener-integration-release
    cluster: gardener-prow-build
    # Run on release branches / adapt this setting and create a new job in case of incompatible changes in tests or go version between the releases
    branches:
    - release-v\d+.\d+
    skip_branches:
    - release-v1.([1-3][0-9]|4[0-6])
    decorate: true
    decoration_config:
      timeout: 20m
      grace_period: 10m
    annotations:
      description: Runs integration tests for gardener releases when merging
    spec:
      containers:
      - name: test-integration
        image: eu.gcr.io/gardener-project/ci-infra/golang-test:v20220517-f80c2bf-1.18
        command:
        - make
        args:
        - test-integration
        resources:
          limits:
            memory: 16Gi
          requests:
            cpu: 4
            memory: 8Gi
