presubmits:
  gardener/gardener:
  - name: pull-gardener-e2e-kind-ha-single-zone-upgrade
    cluster: gardener-prow-build
    always_run: true
    skip_branches:
    - release-v\d+.\d+ # don't run on release branches for now (add a job per branch later)
    decorate: true
    decoration_config:
      timeout: 60m
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests on a Seed with single zone with a Shoot with failure tolerance type 'node' for gardener developments in pull requests
      fork-per-release: "true"
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240703-b85d644-1.22
        command:
        - wrapper.sh
        - bash
        - -c
        - make import-tools-bin ci-e2e-kind-ha-single-zone-upgrade
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 12
            memory: 24Gi
        env:
        - name: SKAFFOLD_UPDATE_CHECK
          value: "false"
        - name: SKAFFOLD_INTERACTIVE
          value: "false"
periodics:
- name: ci-gardener-e2e-kind-ha-single-zone-upgrade
  cluster: gardener-prow-build
  interval: 4h
  extra_refs:
  - org: gardener
    repo: gardener
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 60m
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    description: Runs end-to-end tests on a Seed with single zone with a Shoot with failure tolerance type 'node' for gardener developments periodically
    testgrid-dashboards: gardener-gardener
    testgrid-days-of-results: "60"
    fork-per-release: "true"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240703-b85d644-1.22
      command:
      - wrapper.sh
      - bash
      - -c
      - make import-tools-bin ci-e2e-kind-ha-single-zone-upgrade
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 12
          memory: 24Gi
      env:
      - name: SKAFFOLD_UPDATE_CHECK
        value: "false"
      - name: SKAFFOLD_INTERACTIVE
        value: "false"
