presubmits:
  gardener/gardener:
  - name: pull-gardener-integration
    cluster: gardener-prow-build
    always_run: true
    skip_branches:
    - release-v\d+.\d+ # don't run on release branches for now (add a job per branch later)
    decorate: true
    decoration_config:
      timeout: 20m
      grace_period: 10m
    labels:
      preset-gocache-mounts: "true"
    annotations:
      description: Runs integration tests for gardener developments in pull requests
      fork-per-release: "true"
    spec:
      # For PR jobs, use a read-only service account
      serviceAccountName: gardener-prow-gobuildcache-ro
      containers:
      - name: test-integration
        image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260227-085711a-1.26
        command:
          - make
        args:
        - import-tools-bin
        - test-integration
        resources:
          limits:
            memory: 16Gi
          requests:
            cpu: 5
            memory: 8Gi
        env:
        - name: GOCACHEPROG
          value: "gobuildcache -readonly gs://gardener-prow-gobuildcache"
periodics:
- name: ci-gardener-integration
  cluster: gardener-prow-build
  interval: 2h
  extra_refs:
  - org: gardener
    repo: gardener
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 20m
    grace_period: 10m
  labels:
    preset-gocache-mounts: "true"
  annotations:
    description: Runs integration tests for gardener developments periodically
    testgrid-dashboards: gardener-gardener
    testgrid-days-of-results: "60"
    fork-per-release: "true"
  spec:
    # For periodic jobs, use a read-write service account
    serviceAccountName: gardener-prow-gobuildcache-rw
    containers:
    - name: test-integration
      image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260227-085711a-1.26
      command:
        - make
      args:
        - import-tools-bin
        - test-integration
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: 5
          memory: 8Gi
      env:
      - name: GOCACHEPROG
        value: "gobuildcache gs://gardener-prow-gobuildcache"
