presubmits:
  gardener/gardener:
  - name: pull-gardener-e2e-kind-gardenadm
    cluster: gardener-prow-build
    always_run: false
    skip_if_only_changed: "^(\\.ci|\\.github|\\.ocm|\\.test-defs|docs|logo)/|\\.md$|^(README|LICENSE|VERSION|OWNERS|OWNERS_ALIASES)$"
    skip_branches:
    - release-v\d+.\d+ # don't run on release branches for now (add a job per branch later)
    decorate: true
    decoration_config:
      timeout: 2h
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for gardenadm developments in pull requests
      fork-per-release: "true"
    spec: &e2e-kind-gardenadm-spec
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20251112-67af14d-1.25
        command:
        - wrapper.sh
        - bash
        - -c
        - make import-tools-bin ci-e2e-kind-gardenadm
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 12
            memory: 24Gi
        env:
        - name: SKAFFOLD_UPDATE_CHECK
          value: "false"
        - name: SKAFFOLD_INTERACTIVE
          value: "false"
periodics:
- name: ci-gardener-e2e-kind-gardenadm
  cluster: gardener-prow-build
  interval: 2h
  extra_refs:
  - org: gardener
    repo: gardener
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 2h
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    description: Runs end-to-end tests for gardenadm developments periodically
    testgrid-dashboards: gardener-gardener
    testgrid-days-of-results: "60"
    fork-per-release: "true"
  spec: *e2e-kind-gardenadm-spec
