presubmits:
  gardener/gardener-extension-shoot-rsyslog-relp:
  - name: pull-gardener-extension-shoot-rsyslog-relp-e2e-kind
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 60m
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for Gardener extension shoot-rsyslog-relp developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240408-63fb85b-1.22
        command:
        - wrapper.sh
        - bash
        - -c
        - make ci-e2e-kind
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 6
            memory: 18Gi
        env:
        - name: SKAFFOLD_UPDATE_CHECK
          value: "false"
        - name: SKAFFOLD_INTERACTIVE
          value: "false"
periodics:
- name: ci-gardener-extension-shoot-rsyslog-relp-e2e-kind
  cluster: gardener-prow-build
  interval: 24h
  extra_refs:
  - org: gardener
    repo: gardener-extension-shoot-rsyslog-relp
    base_ref: main
  decorate: true
  decoration_config:
    timeout: 60m
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    description: Runs end-to-end tests for Gardener extension shoot-rsyslog-relp developments periodically
    testgrid-dashboards: gardener-extension-shoot-rsyslog-relp
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240408-63fb85b-1.22
      command:
      - wrapper.sh
      - bash
      - -c
      - make ci-e2e-kind
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 6
          memory: 18Gi
      env:
      - name: SKAFFOLD_UPDATE_CHECK
        value: "false"
      - name: SKAFFOLD_INTERACTIVE
        value: "false"
