presubmits:
  gardener/gardener-extension-shoot-rsyslog-relp:
  - name: pull-gardener-extension-shoot-rsyslog-relp-integration
    cluster: gardener-prow-build
    always_run: true
    skip_branches:
    - release-v\d+.\d+ # don't run on release branches for now (add a job per branch later)
    decorate: true
    decoration_config:
      timeout: 20m
      grace_period: 10m
    annotations:
      description: Runs integration tests for Gardener extension shoot-rsyslog-relp developments in pull requests
    spec:
      containers:
      - name: test-integration
        image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240710-e8976fd-1.22
        command:
        - make
        args:
        - test-integration
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 2
            memory: 1Gi
periodics:
- name: ci-gardener-extension-shoot-rsyslog-relp-integration
  cluster: gardener-prow-build
  interval: 4h
  extra_refs:
  - org: gardener
    repo: gardener-extension-shoot-rsyslog-relp
    base_ref: main
  decorate: true
  decoration_config:
    timeout: 20m
    grace_period: 10m
  annotations:
    description: Runs integration tests for Gardener extension shoot-rsyslog-relp developments periodically
    testgrid-dashboards: gardener-extension-shoot-rsyslog-relp
    testgrid-days-of-results: "60"
  spec:
    containers:
    - name: test-integration
      image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240710-e8976fd-1.22
      command:
      - make
      args:
      - test-integration
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 2
          memory: 1Gi
