presubmits:
  gardener/gardener-extension-shoot-dns-service:
  - name: pull-extension-shoot-dns-service-unit
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 20m
      grace_period: 10m
    annotations:
      description: Runs unit tests for gardener-extension-shoot-dns-service developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20251111-6a6ac66-1.25
        command:
        - make
        args:
        - import-tools-bin
        - verify-extended
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
periodics:
- name: ci-extension-shoot-dns-service-unit
  cluster: gardener-prow-build
  interval: 4h
  extra_refs:
  - org: gardener
    repo: gardener-extension-shoot-dns-service
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 20m
    grace_period: 10m
  annotations:
    description: Periodically runs unit tests for extension-shoot-dns-service master branch
    testgrid-dashboards: gardener-extension-shoot-dns-service
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20251111-6a6ac66-1.25
      command:
      - make
      args:
      - import-tools-bin
      - verify-extended
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
