# Plugin configuration
---
triggers:
- repos:
  - gardener/ci-infra
  - gardener/gardener
  only_org_members: true

approve:
- repos:
  - gardener/ci-infra
  lgtm_acts_as_approve: true
  require_self_approval: true
  commandHelpLink: "https://prow.gardener.cloud/command-help"
  pr_process_link: "https://gardener.cloud/docs/contribute/#pull-request-checklist"
- repos:
  - gardener/gardener
  lgtm_acts_as_approve: false
  require_self_approval: true
  commandHelpLink: "https://prow.gardener.cloud/command-help"
  pr_process_link: "https://gardener.cloud/docs/contribute/#pull-request-checklist"

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

label:
  additional_labels:
    # These labels are used to make Tide merge with a non-default merge method
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash

lgtm:
- repos:
  - gardener/ci-infra
  - gardener/gardener
  review_acts_as_lgtm: true

blunderbuss:
  max_request_count: 2
  use_status_availability: true

heart:
  commentregexp: ".*"

slack:
  # warn about manual merges
  mergewarnings:
  - repos:
    - gardener/ci-infra
    channels:
    - gardener-prow-alerts
    exempt_users:
    - gardener-prow[bot]
  - repos:
    - gardener/gardener
    channels:
    - gardener-prow-alerts
    exempt_users:
    - gardener-prow[bot]
    - gardener-robot-ci-1
    - gardener-robot-ci-2
    - gardener-robot-ci-3

repo_milestone:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones. You may need to specify the page number.
  # curl -H "Authorization: token <token>" "https://api.github.com/orgs/<org-name>/teams?page=N"
  gardener/ci-infra:
    maintainers_id: 5415312
    maintainers_team: ci-infra-maintainers
  gardener/gardener:
    maintainers_id: 2609205
    maintainers_team: gardener-maintainers

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
      clusters:
        gardener-prow-trusted:
        - prow
    config/prow/plugins.yaml:
      name: plugins
      clusters:
        gardener-prow-trusted:
        - prow
    config/jobs/**/*.yaml:
      name: job-config
      gzip: true
      clusters:
        gardener-prow-trusted:
        - prow

welcome:
- repos:
  - gardener/ci-infra
  - gardener/gardener
  message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> ðŸŽ‰. Please refer to our [pull request process documentation](https://gardener.cloud/docs/contribute/#pull-request-checklist) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://prow.k8s.io/command-help). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>Thank you, and welcome to Gardener. :smiley:"

require_matching_label:
- missing_label: do-not-merge/needs-kind
  org: gardener
  repo: ci-infra
  prs: true
  regexp: ^kind/
- missing_label: do-not-merge/needs-kind
  org: gardener
  repo: gardener
  prs: true
  regexp: ^kind/

retitle:
  allow_closed_issues: true

# Enabled plugins per repo.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
plugins:
  gardener/ci-infra:
    plugins:
    - approve
    - assign
    - blunderbuss
    - config-updater
    - dog
    - golint
    - heart
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - lifecycle
    - mergecommitblocker
    - milestone
    - override
    - owners-label
    - require-matching-label
    - retitle
    - shrug
    - size
    - skip
    - slackevents
    - transfer-issue
    - trick-or-treat
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks
  gardener/gardener:
    plugins:
    - approve
    - assign
    - blunderbuss
    - dog
    - golint
    - heart
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - lifecycle
    - mergecommitblocker
    - milestone
    - override
    - owners-label
    - require-matching-label
    - retitle
    - shrug
    - size
    - skip
    - slackevents
    - transfer-issue
    - trick-or-treat
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks

external_plugins:
  gardener/ci-infra:
  - name: cla-assistant
    events:
      - issue_comment
      - pull_request_review
      - pull_request_review_comment
      - status
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request
  gardener/gardener:
  - name: cla-assistant
    events:
      - issue_comment
      - pull_request_review
      - pull_request_review_comment
      - status
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request
