# Plugin configuration
---
triggers:
- repos:
  - gardener/ci-infra
  only_org_members: true
#  join_org_url: "https://git.k8s.io/community/community-membership.md#member"

#owners:
#  mdyamlrepos:
#  - kubernetes/website
#  skip_collaborators:
#  - kubernetes-sigs/contributor-playground

approve:
- repos:
  - gardener/ci-infra
  require_self_approval: false
  lgtm_acts_as_approve: true

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

label:
  additional_labels:
    # These labels are used to make Tide merge with a non-default merge method
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash

lgtm:
- repos:
  - gardener/ci-infra
  review_acts_as_lgtm: true

#blockades:
#- repos:
#  - kubernetes/kubernetes
#  blockregexps:
#  - ^examples/
#  explanation: "examples/ has moved to https://github.com/kubernetes/examples/"

blunderbuss:
  max_request_count: 2
  use_status_availability: true

heart:
  commentregexp: ".*"

#slack:
#  mergewarnings:
#  - repos:
#    - kubernetes/community
#    - kubernetes/org
#    channels:
#    - sig-contribex
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/enhancements
#    channels:
#    - enhancements
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/utils
#    - kubernetes/component-helpers
#    channels:
#    - sig-architecture
#    exempt_users:
#    - k8s-ci-robot
#    - k8s-publishing-bot
#  - repos:
#    - kubernetes/api
#    - kubernetes/apiextensions-apiserver
#    - kubernetes/apimachinery
#    - kubernetes/apiserver
#    - kubernetes/client-go
#    - kubernetes/code-generator
#    - kubernetes/component-base
#    - kubernetes/controller-manager
#    - kubernetes/kube-aggregator
#    - kubernetes/kube-controller-manager
#    - kubernetes/sample-apiserver
#    - kubernetes/sample-controller
#    channels:
#    - sig-api-machinery
#    exempt_users:
#    - k8s-publishing-bot
#  - repos:
#    - kubernetes/pod-security-admission
#    channels:
#    - sig-auth
#    exempt_users:
#    - k8s-publishing-bot
#  - repos:
#    - kubernetes/kubernetes
#    channels:
#    - github-management
#    exempt_users:
#    - k8s-ci-robot # future home of tide
#    - k8s-release-robot # anago
#    exempt_branches:
#        feature-serverside-apply:
#            - lavalamp # feature-serverside-apply "branch manager"
#            - apelisse # feature-serverside-apply "branch manager"
#        feature-rate-limiting:
#            - lavalamp # feature-rate-limiting "branch manager"
#            - deads2k # feature-rate-limiting "branch manager"
#  - repos:
#    - kubernetes/test-infra
#    channels:
#    - testing-ops
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/sig-release
#    channels:
#    - release-management
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/release
#    channels:
#    - release-management
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/k8s.io
#    channels:
#    - sig-k8s-infra
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/kops
#    channels:
#    - kops-dev
#    exempt_users:
#    - k8s-ci-robot
#  - repos:
#    - kubernetes/cluster-api-provider-aws
#    channels:
#    - cluster-api-aws
#    exempt_users:
#    - k8s-ci-robot

#milestone_applier:
#  kubernetes/enhancements:
#    master: v1.23
#  kubernetes/kubernetes:
#    master: v1.23
#    release-1.22: v1.22
#    release-1.21: v1.21
#    release-1.20: v1.20
#    release-1.19: v1.19
#  kubernetes/org:
#    main: v1.23
#  kubernetes/release:
#    master: v1.23
#  kubernetes/sig-release:
#    master: v1.23
#  kubernetes/test-infra:
#    master: v1.23
#  kubernetes/k8s.io:
#    main: v1.23
#  kubernetes/kops:
#    master: v1.23
#    release-1.22: v1.22
#    release-1.21: v1.21
#    release-1.20: v1.20
#    release-1.19: v1.19
#    release-1.18: v1.18
#    release-1.17: v1.17
#    release-1.16: v1.16
#  kubernetes-sigs/cluster-api:
#    main: v0.4
#    release-0.4: v0.4
#    operator-0.4: v0.4 # Remove this when it gets merged back.
#    release-0.3: v0.3
#  kubernetes-sigs/cluster-api-provider-aws:
#    main: v0.7.0
#    release-0.6: v0.6.x
#  kubernetes-sigs/cluster-api-provider-azure:
#    main: v0.5
#    release-0.4: v0.4.16
#  kubernetes-sigs/cluster-api-provider-digitalocean:
#    main: v0.5.0
#    release-0.4: v0.4.3
#  kubernetes-sigs/cluster-api-provider-gcp:
#    main: v0.4
#    release-0.4: v0.4
#    release-0.3: v0.3
#  kubernetes-sigs/boskos:
#    master: v1.23
#  kubernetes-sigs/controller-runtime:
#    master: v0.10.x
#    release-0.9: v0.9.x
#    release-0.8: v0.8.x
#    release-0.7: v0.7.x
#    release-0.6: v0.6.x
#    release-0.5: v0.5.x
#  kubernetes/website:
#    dev-1.23: 1.23

#repo_milestone:
#  # Default maintainer
#  '':
#    # You can curl the following endpoint in order to determine the github ID of your team
#    # responsible for maintaining the milestones. You may need to specify the page number.
#    # curl -H "Authorization: token <token>" "https://api.github.com/orgs/<org-name>/teams?page=N"
#    maintainers_id: 2460384
#    maintainers_team: milestone-maintainers
#  kubernetes-sigs/controller-runtime:
#    maintainers_id: 2785806
#    maintainers_team: controller-runtime-maintainers
#    maintainers_friendly_name: Controller Runtime Maintainers
#  kubernetes-sigs/cluster-api:
#    maintainers_id: 3058957
#    maintainers_team: cluster-api-maintainers
#    maintainers_friendly_name: Cluster API Maintainers
#  kubernetes-sigs/cluster-api-provider-aws:
#    maintainers_id: 2830895
#    maintainers_team: cluster-api-provider-aws-maintainers
#    maintainers_friendly_name: Cluster API Provider AWS Maintainers
#  kubernetes-sigs/cluster-api-provider-azure:
#    maintainers_id: 3063852
#    maintainers_team: cluster-api-provider-azure-maintainers
#    maintainers_friendly_name: Cluster API Provider Azure Maintainers
#  kubernetes-sigs/cluster-api-provider-digitalocean:
#    maintainers_id: 2978501
#    maintainers_team: cluster-api-provider-digitalocean-maintainers
#    maintainers_friendly_name: Cluster API Provider DigitalOcean Maintainers
#  kubernetes-sigs/cluster-api-provider-gcp:
#    maintainers_id: 2829767
#    maintainers_team: cluster-api-provider-gcp-maintainers
#    maintainers_friendly_name: Cluster API Provider GCP Maintainers
#  kubernetes-sigs/cluster-api-provider-nested:
#    maintainers_id: 4158805
#    maintainers_team: cluster-api-provider-nested-maintainers
#    maintainers_friendly_name: Cluster API Provider Nested Maintainers
#  kubernetes-sigs/cluster-api-provider-vsphere:
#    maintainers_id: 2850058
#    maintainers_team: cluster-api-provider-vsphere-maintainers
#    maintainers_friendly_name: Cluster API Provider vSphere Maintainers
#  kubernetes/community:
#    maintainers_id: 3169231
#    maintainers_team: community-milestone-maintainers
#    maintainers_friendly_name: Community Milestone Maintainers
#  kubernetes/kops:
#    maintainers_id: 2060651
#    maintainers_team: kops-maintainers
#    maintainers_friendly_name: Kops Maintainers
#  kubernetes/org:
#    maintainers_id: 2842373
#    maintainers_team: owners
#    maintainers_friendly_name: GitHub Admin Team
#  kubernetes/website:
#    maintainers_id: 3175912
#    maintainers_team: website-milestone-maintainers
#    maintainers_friendly_name: Website milestone maintainers
#  kubernetes/kubeadm:
#    maintainers_id: 2195382
#    maintainers_team: kubeadm-maintainers
#    maintainers_friendly_name: Kubeadm maintainers
#  kubernetes-sigs/kubebuilder:
#    maintainers_id: 2688053
#    maintainers_team: kubebuilder-maintainers
#    maintainers_friendly_name: Kubebuilder Maintainers

#project_config:
#  project_org_configs:
#    kubernetes:
#      org_maintainers_team_id: 3162587 # sig-testing-dummy-project-team
#      org_default_column_map:
#        test-infra-dummy-testing-project-plugin:
#          To do
#        KEP Implementation Tracking:
#          To do
#      project_repo_configs:
#        kubernetes:
#          repo_maintainers_team_id: 2460384 # milestone-maintainers
#          repo_default_column_map:
#            component-base:
#              To do
#            Workloads:
#              Backlog
#        website:
#          repo_maintainers_team_id: 3175912 # website-milestone-maintainers
#          repo_default_column_map:
#            component-base:
#              To do
#            Doc Writing and Editing:
#              To do

config_updater:
  maps:
#    label_sync/labels.yaml:
#      name: label-config
#      clusters:
#        test-infra-trusted:
#          - test-pods
    config/prow/config.yaml:
      name: config
      clusters:
        test-infra-trusted:
        - prow
    config/prow/plugins.yaml:
      name: plugins
      clusters:
        test-infra-trusted:
        - prow
    config/jobs/**/*.yaml:
      name: job-config
      gzip: true
      clusters:
        test-infra-trusted:
        - prow

#welcome:
#- repos:
#  - kubernetes
#  - kubernetes-client
#  - kubernetes-csi
#  - kubernetes-sigs
#  message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> ðŸŽ‰. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing. <br><br>If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). Also, for tips and tricks in the contribution process you may want to read the [Kubernetes contributor cheat sheet](https://git.k8s.io/community/contributors/guide/contributor-cheatsheet/README.md). We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Kubernetes. :smiley:"

#require_matching_label:
#- missing_label: do-not-merge/needs-kind
#  org: gardener
#  repo: gardener
#  prs: true
#  regexp: ^kind/

retitle:
  allow_closed_issues: true

#cherry_pick_unapproved:
#  comment: |
#    This cherry pick PR is for a release branch and has not yet been approved by [Release Managers](https://git.k8s.io/sig-release/release-managers.md).
#    Adding the `do-not-merge/cherry-pick-not-approved` label.
#
#    To merge this cherry pick, it must first be approved (`/lgtm` + `/approve`) by the relevant OWNERS.
#
#    **AFTER** it has been approved by code owners, please ping the **kubernetes/release-managers** team in a comment to request a cherry pick review.
#
#    (For details on the patch release process and schedule, see the [Patch Releases](https://git.k8s.io/sig-release/releases/patch-releases.md) page.)

# Enabled plugins per repo.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
plugins:
  gardener/ci-infra:
    plugins:
    - approve
    - assign
    - blockade
    - blunderbuss
    - config-updater
    - dog
    - golint
    - heart
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - lifecycle
    - mergecommitblocker
    - milestone
    - override
    - owners-label
    - retitle
    - shrug
    - size
    - skip
    - transfer-issue
    - trick-or-treat
    - trigger
    - verify-owners
    - wip
    - yuks

external_plugins:
  gardener/ci-infra:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request
