presubmits:
  gardener/gardener-landscape-kit:
  - name: pull-gardener-landscape-kit-e2e-kind
    cluster: gardener-prow-build
    always_run: false
    skip_if_only_changed: "^(\\.github|docs|example)/|\\.md$|^(LICENSE|VERSION|OWNERS|OWNERS_ALIASES)$"
    skip_branches:
    - release-v\d+.\d+ # don't run on release branches for now (add a job per branch later)
    decorate: true
    decoration_config:
      timeout: 1h
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for gardener-landscape-kit developments in pull requests
      fork-per-release: "true"
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20260216-18b2c13-1.26
        command:
          - wrapper.sh
          - bash
          - -c
          - make ci-e2e-kind
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 6
            memory: 16Gi
        env:
        - name: SKAFFOLD_UPDATE_CHECK
          value: "false"
        - name: SKAFFOLD_INTERACTIVE
          value: "false"
periodics:
- name: ci-gardener-landscape-kit-e2e-kind
  cluster: gardener-prow-build
  interval: 2h
  extra_refs:
  - org: gardener
    repo: gardener-landscape-kit
    base_ref: main
  decorate: true
  decoration_config:
    timeout: 1h
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    description: Runs end-to-end tests for gardener-landscape-kit developments periodically
    testgrid-dashboards: gardener-landscape-kit
    testgrid-days-of-results: "60"
    fork-per-release: "true"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20260216-18b2c13-1.26
      command:
      - wrapper.sh
      - bash
      - -c
      - make ci-e2e-kind
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 6
          memory: 16Gi
      env:
      - name: SKAFFOLD_UPDATE_CHECK
        value: "false"
      - name: SKAFFOLD_INTERACTIVE
        value: "false"
