presubmits:
  gardener/gardener-landscape:
  - name: pull-gardener-landscape-unit
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 40m
      grace_period: 10m
    annotations:
      description: Runs unit tests for Gardener extension image-rewriter developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20251111-58c1149-1.24
        command:
        - make
        args:
        - import-tools-bin
        - verify-extended
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 2
            memory: 1Gi
periodics:
- name: ci-gardener-landscape-unit
  cluster: gardener-prow-build
  interval: 24h
  extra_refs:
  - org: gardener
    repo: gardener-landscape
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 40m
    grace_period: 10m
  annotations:
    description: Runs unit tests for Gardener extension image-rewriter developments periodically
    testgrid-dashboards: gardener-landscape
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20251111-58c1149-1.24
      command:
      - make
      args:
      - import-tools-bin
      - verify-extended
      resources:
        limits:
          memory: 3Gi
        requests:
          cpu: 2
          memory: 1Gi
