presubmits:
  gardener/ci-infra:
  # Please keep this in sync with the `ci-infra-prow-checkconfig-{trusted,build}` jobs
  - name: pull-ci-infra-prow-checkconfig
    cluster: gardener-prow-build
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    decorate: true
    annotations:
      description: Runs checkconfig to validate changes to job configs, config.yaml and friends
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20240515-dd5d0eeaa
        command:
        - checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --job-config-path=config/jobs
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
        - --warnings=duplicate-job-refs
  - name: pull-ci-infra-prow-go-tests
    cluster: gardener-prow-build
    decorate: true
    always_run: true
    annotations:
      description: Runs go tests for prow developments in ci-infra 
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240516-8771c6a-1.22
        command:
        - make
        args:
        - verify
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 4
            memory: 2Gi
  - name: pull-ci-infra-verify-image-build
    cluster: gardener-prow-build
    always_run: true
    annotations:
      description: Verify ci-infra image build on pull requests to master branch
    decorate: true
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v1.23.0
        command:
        - /kaniko/executor
        args:
        - --context=/home/prow/go/src/github.com/gardener/ci-infra
        - --dockerfile=Dockerfile
        - --no-push
        - --registry-mirror=registry-docker-io.kube-system.svc.cluster.local:5000
        - --insecure-registry=registry-docker-io.kube-system.svc.cluster.local:5000
        - --build-arg=GOPROXY=http://athens-proxy.athens.svc.cluster.local,direct
        resources:
          requests:
            cpu: 6
            memory: 2Gi
  - name: pull-ci-infra-check-renovate-config
    cluster: gardener-prow-build
    always_run: true
    annotations:
      description: Validates renovate config on pull requests to master branch
    decorate: true
    spec:
      containers:
      - name: renovate
        image: ghcr.io/renovatebot/renovate:37.366.1
        command:
        - renovate-config-validator
