postsubmits:
  gardener/ci-infra:
  - name: post-ci-infra-deploy-prow
    cluster: gardener-prow-trusted
    run_if_changed: 'config/prow/(cluster/|deploy.sh)'
    decorate: true
    branches:
    - ^master$
    max_concurrency: 1
    reporter_config:
      slack:
        channel: prow-alerts
        job_states_to_report:
        - success
        - failure
        - aborted
        - error
        report_template: |
          *Deploying prow*
          *Job:* {{.Spec.Job}} ({{.Spec.Type}})
          *Status:* {{.Status.State}}
          *Commit:* <{{.Spec.Refs.BaseLink}}|{{printf "%.7s" .Spec.Refs.BaseSHA}}>
          *<{{.Status.URL}}|Spyglass> | <https://prow.gardener.cloud/?job={{.Spec.Job}}|Deck>*
    annotations:
      description: Deploys the configured version of prow by running config/prow/deploy.sh
      testgrid-create-test-group: "false"
    spec:
      serviceAccountName: deployer
      containers:
      - image: bitnami/kubectl:1.24.7
        command:
        - config/prow/deploy.sh
        env:
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config"
        volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
