presubmits:
  gardener/ci-infra:
  # Please keep this in sync with the `ci-infra-prow-checkconfig-{trusted,build}` jobs
  - name: pull-ci-infra-prow-checkconfig
    cluster: gardener-prow-build
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    decorate: true
    annotations:
      description: Runs checkconfig to validate changes to job configs, config.yaml and friends
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/checkconfig:v20260220-ea4b6a3dc
        command:
        - checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --job-config-path=config/jobs
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
        - --warnings=duplicate-job-refs
  - name: pull-ci-infra-prow-go-tests
    cluster: gardener-prow-build
    decorate: true
    skip_if_only_changed: '^(.github|clusters|config|deploy|images)\/'
    annotations:
      description: Runs go tests for prow developments in ci-infra 
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260223-b4e5c83-1.26
        command:
        - make
        args:
        - verify
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 4
            memory: 2Gi
