postsubmits:
  gardener/ci-infra:
  - name: post-ci-infra-copy-images
    cluster: gardener-prow-trusted
    run_if_changed: '^config\/images\/'
    branches:
    - ^master$
    annotations:
      description: Copy images from DockerHub
      testgrid-dashboards: gardener-ci-infra
      testgrid-days-of-results: "60"
    decorate: true
    max_concurrency: 1
    reporter_config:
      slack:
        channel: prow-alerts
    spec:
      containers:
      - name: copy-images
        image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/copy-images:v20240129-fbf85e1
        command:
        - ./config/images/copy-images.sh
        args:
        - ./config/images/images.yaml
        volumeMounts:
        - name: docker-config
          mountPath: /root/.docker
      volumes:
      - name: docker-config
        secret:
          secretName: gardener-prow-gcr-docker-config
