presubmits:
  gardener/gardener-extension-networking-cilium:
  - name: pull-extension-networking-cilium
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 30m
      grace_period: 10m
    annotations:
      description: Runs unit tests for gardener-extension-networking-cilium developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240116-fde669d-1.21
        command:
        - make
        args:
        - verify-extended
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 2
            memory: 1Gi
periodics:
- name: ci-extension-networking-cilium
  cluster: gardener-prow-build
  interval: 4h
  extra_refs:
  - org: gardener
    repo: gardener-extension-networking-cilium
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 30m
    grace_period: 10m
  annotations:
    description: Periodically runs unit tests for gardener-extension-networking-cilium master branch
    testgrid-dashboards: gardener-extension-networking-cilium
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240116-fde669d-1.21
      command:
      - make
      args:
      - verify-extended
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 2
          memory: 1Gi
