presubmits:
  gardener/gardener-extension-networking-cilium:
  - name: pull-extension-networking-cilium-e2e-kind
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 60m
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for gardener-extension-networking-cilium developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240528-47bd59a-1.22
        command:
        - wrapper.sh
        - bash
        - -c
        - |
          set -o nounset
          set -o pipefail
          set -o errexit

          # https://github.com/kubernetes/test-infra/issues/23741
          iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

          # run test
          make test-e2e-local
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 6
            memory: 18Gi
        env:
        - name: SKAFFOLD_UPDATE_CHECK
          value: "false"
        - name: SKAFFOLD_INTERACTIVE
          value: "false"
periodics:
- name: ci-extension-networking-cilium-e2e-kind
  cluster: gardener-prow-build
  interval: 24h
  extra_refs:
  - org: gardener
    repo: gardener-extension-networking-cilium
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 60m
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    description: Runs end-to-end tests for gardener-extension-networking-cilium developments periodically
    testgrid-dashboards: gardener-extension-networking-cilium
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240528-47bd59a-1.22
      command:
      - wrapper.sh
      - bash
      - -c
      - |
        set -o nounset
        set -o pipefail
        set -o errexit

        # https://github.com/kubernetes/test-infra/issues/23741
        iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

        # run test
        make test-e2e-local
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 6
          memory: 18Gi
      env:
      - name: SKAFFOLD_UPDATE_CHECK
        value: "false"
      - name: SKAFFOLD_INTERACTIVE
        value: "false"
