presubmits:
  gardener/dependency-watchdog:
    - name: pull-dependency-watchdog-e2e-kind
      cluster: gardener-prow-build
      always_run: true
      skip_branches:
        - release-v\d+.\d+ # don't run on release branches for now (add a job per branch later)
      decorate: true
      decoration_config:
        timeout: 60m
        grace_period: 15m
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        description: Runs KIND cluster based e2e tests for dependency watchdog developments in pull requests
      spec:
        containers:
          - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240424-2bd443b-1.22
            command:
              - wrapper.sh
              - bash
              - -c
              - make kind-tests
            # we need privileged mode in order to do docker in docker
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 6
                memory: 18Gi
periodics:
  - name: ci-dependency-watchdog-e2e-kind
    cluster: gardener-prow-build
    interval: 4h
    extra_refs:
      - org: gardener
        repo: dependency-watchdog
        base_ref: master
    decorate: true
    decoration_config:
      timeout: 60m
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs KIND cluster based e2e tests for dependency watchdog developments periodically
      testgrid-dashboards: gardener-dependency-watchdog
      testgrid-days-of-results: "60"
    spec:
      containers:
        - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240424-2bd443b-1.22
          command:
            - wrapper.sh
            - bash
            - -c
            - make kind-tests
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 6
              memory: 18Gi