presubmits:
  gardener/dependency-watchdog:
  - name: pull-dependency-watchdog-check-vulnerabilities
    cluster: gardener-prow-build
    skip_if_only_changed: "^docs/|\\.(md|yaml)$"
    decorate: true
    decoration_config:
      timeout: 15m
      grace_period: 5m
    optional: true
    branches:
    - ^master$
    spec:
      containers:
      - name: test
        image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240722-3879074-1.22
        command:
        - make
        args:
        - check-vulnerabilities
periodics:
- name: ci-dependency-watchdog-check-vulnerabilities
  cluster: gardener-prow-build
  interval: 24h
  extra_refs:
  - org: gardener
    repo: dependency-watchdog
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 15m
    grace_period: 5m
  annotations:
    description: Runs go vulnerability checker for dependency-watchdog periodically
    testgrid-dashboards: gardener-dependency-watchdog
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20240722-3879074-1.22
      command:
      - make
      args:
      - check-vulnerabilities
