apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: cherrypicker
  labels:
    app: cherrypicker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cherrypicker
  template:
    metadata:
      labels:
        app: cherrypicker
    spec:
      serviceAccountName: ""
      terminationGracePeriodSeconds: 180
      containers:
      - name: cherrypicker
        image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/cherrypicker:v20240223-f63e8ac
        imagePullPolicy: Always
        args:
        - --github-token-path=/etc/github/token
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --dry-run=false
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: github-token
          mountPath: /etc/github
          readOnly: true
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      volumes:
      - name: tmp
        emptyDir: {}
      - name: hmac
        secret:
          secretName: hmac-token
      - name: github-token
        secret:
          secretName: github-token
