presubmits:
  gardener/landscaper:
  - name: pull-landscaper-e2e-kind
    cluster: gardener-prow-build
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h30m0s
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for landscaper developments in pull requests
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/krte:v20231206-f7b83ffbe6-master
        command:
        - wrapper.sh
        - bash
        - -c
        - |
          set -o nounset
          set -o pipefail
          set -o errexit

          # https://github.com/kubernetes/test-infra/issues/23741
          iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

          # run test
          .ci/prow/integration-test
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 6
            memory: 18Gi
