presubmits:
  gardener/cert-management:
  - name: pull-cert-management-integration
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 30m
      grace_period: 10m
    annotations:
      description: Runs integration tests for cert-management developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260219-2111b43-1.26
        command:
        - make
        args:
        - import-tools-bin
        - test-integration
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
periodics:
- name: ci-cert-management-integration
  cluster: gardener-prow-build
  interval: 24h
  extra_refs:
  - org: gardener
    repo: cert-management
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 30m
    grace_period: 10m
  annotations:
    description: Periodically runs integration tests for cert-management master branch
    testgrid-dashboards: cert-management
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260219-2111b43-1.26
      command:
      - make
      args:
      - import-tools-bin
      - test-integration
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
