presubmits:
  gardener/cert-management:
  - name: pull-cert-management-e2e-kind
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 60m
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for cert-management developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240828-9580330-1.22
        command:
        - wrapper.sh
        - bash
        - -c
        - |
          set -o nounset
          set -o pipefail
          set -o errexit

          # run test
          make test-e2e-local
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
            memory: 8Gi
        env:
        - name: SKAFFOLD_UPDATE_CHECK
          value: "false"
        - name: SKAFFOLD_INTERACTIVE
          value: "false"
periodics:
- name: ci-cert-management-e2e-kind
  cluster: gardener-prow-build
  interval: 24h
  extra_refs:
  - org: gardener
    repo: cert-management
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 60m
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    description: Runs end-to-end tests for cert-management developments periodically
    testgrid-dashboards: cert-management
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20240828-9580330-1.22
      command:
      - wrapper.sh
      - bash
      - -c
      - |
        set -o nounset
        set -o pipefail
        set -o errexit

          # run test
          make test-e2e-local
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
            memory: 8Gi
      env:
      - name: SKAFFOLD_UPDATE_CHECK
        value: "false"
      - name: SKAFFOLD_INTERACTIVE
        value: "false"