dashboard_groups:
- name: gardener
  dashboard_names:
    - gardener-gardener
    - gardener-ci-infra
    - gardener-extension-registry-cache
    - gardener-extension-shoot-oidc-service
    - gardener-dependency-watchdog
    - gardener-etcd-druid
    - gardener-extension-networking-cilium
    - gardener-extension-networking-calico
    - gardener-extension-shoot-networking-filter
    - gardener-extension-shoot-rsyslog-relp
    - gardener-discovery-server

dashboards:
- name: gardener-gardener
- name: gardener-ci-infra
- name: gardener-extension-registry-cache
- name: gardener-extension-shoot-oidc-service
- name: gardener-dependency-watchdog
- name: gardener-etcd-druid
- name: gardener-extension-networking-cilium
- name: gardener-extension-networking-calico
- name: gardener-extension-shoot-networking-filter
- name: gardener-extension-shoot-rsyslog-relp
- name: gardener-discovery-server
