presubmits:
  gardener/diki-operator:
  - name: pull-diki-operator-unit
    cluster: gardener-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 20m
      grace_period: 10m
    annotations:
      description: Runs unit tests for diki-operator developments in pull requests
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260227-085711a-1.25
        command:
        - make
        args:
        - import-tools-bin
        - verify-extended
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 2
            memory: 1Gi
periodics:
- name: ci-diki-operator-unit
  cluster: gardener-prow-build
  interval: 4h
  extra_refs:
  - org: gardener
    repo: diki-operator
    base_ref: main
  decorate: true
  decoration_config:
    timeout: 20m
    grace_period: 10m
  annotations:
    description: Periodically runs unit tests for diki-operator main branch
    testgrid-dashboards: diki-operator
    testgrid-days-of-results: "60"
  spec:
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260227-085711a-1.25
      command:
      - make
      args:
      - import-tools-bin
      - verify-extended
      resources:
        limits:
          memory: 3Gi
        requests:
          cpu: 2
          memory: 1Gi
