periodics:
- name: ci-gardener-triage-robot-cla
  interval: 10m
  cluster: gardener-prow-trusted
  decorate: true
  annotations:
    description: Trigger recheck of CLAs for open PRs without an CLA label
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20211220-180c042a80
      command:
      - /app/robots/commenter/app.binary
      args:
      - |-
        --query=repo:gardener/ci-infra
        is:pr
        is:open
        -label:"cla: no"
        -label:"cla: yes"
      - --updated=10m
      - --token=/etc/github/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=Unknown CLA label state. Rechecking at cla-assistant.io.
        /cla
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: github-token
        mountPath: /etc/github
        readOnly: true
    volumes:
    - name: github-token
      secret:
        secretName: github-token
