periodics:
- name: ci-gardener-triage-robot-issue-close
  interval: 1h
  cluster: gardener-prow-trusted
  decorate: true
  reporter_config:
    slack:
      channel: prow-alerts
  annotations:
    description: Closes rotten issues after 30d of inactivity
    testgrid-create-test-group: "false"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240210-3c4f626498
      command:
      - commenter
      args:
      - |-
        --query=repo:gardener/ci-infra
        repo:gardener/gardener
        repo:gardener/gardener-extension-registry-cache
        repo:gardener/dependency-watchdog
        is:issue
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=The Gardener project currently lacks enough active contributors to adequately respond to all issues.
        This bot triages issues according to the following rules:
        - After 90d of inactivity, `lifecycle/stale` is applied
        - After 30d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 30d of inactivity since `lifecycle/rotten` was applied, the issue is closed
        
        You can:
        - Reopen this issue with `/reopen`
        - Mark this issue as fresh with `/remove-lifecycle rotten`

        /close
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token

- name: ci-gardener-triage-robot-issue-rotten
  interval: 1h
  cluster: gardener-prow-trusted
  decorate: true
  reporter_config:
    slack:
      channel: prow-alerts
  annotations:
    description: Adds lifecycle/rotten to stale issues after 30d of inactivity
    testgrid-create-test-group: "false"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240210-3c4f626498
      command:
      - commenter
      args:
      - |-
        --query=repo:gardener/ci-infra
        repo:gardener/gardener
        repo:gardener/gardener-extension-registry-cache
        repo:gardener/dependency-watchdog
        is:issue
        -label:lifecycle/frozen
        label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=The Gardener project currently lacks enough active contributors to adequately respond to all issues.
        This bot triages issues according to the following rules:
        - After 90d of inactivity, `lifecycle/stale` is applied
        - After 30d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 30d of inactivity since `lifecycle/rotten` was applied, the issue is closed
        
        You can:
        - Mark this issue as fresh with `/remove-lifecycle rotten`
        - Close this issue with `/close`

        /lifecycle rotten
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token

- name: ci-gardener-triage-robot-issue-stale
  interval: 1h
  cluster: gardener-prow-trusted
  decorate: true
  reporter_config:
    slack:
      channel: prow-alerts
  annotations:
    description: Adds lifecycle/stale to issues after 90d of inactivity
    testgrid-create-test-group: "false"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240210-3c4f626498
      command:
      - commenter
      args:
      - |-
        --query=repo:gardener/ci-infra
        repo:gardener/gardener
        repo:gardener/gardener-extension-registry-cache
        repo:gardener/dependency-watchdog
        is:issue
        -label:lifecycle/frozen
        -label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=2160h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=The Gardener project currently lacks enough active contributors to adequately respond to all issues.
        This bot triages issues according to the following rules:
        - After 90d of inactivity, `lifecycle/stale` is applied
        - After 30d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 30d of inactivity since `lifecycle/rotten` was applied, the issue is closed
        
        You can:
        - Mark this issue as fresh with `/remove-lifecycle stale`
        - Mark this issue as rotten with `/lifecycle rotten`
        - Close this issue with `/close`

        /lifecycle stale
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token

- name: ci-gardener-triage-robot-pr-close
  interval: 1h
  cluster: gardener-prow-trusted
  decorate: true
  reporter_config:
    slack:
      channel: prow-alerts
  annotations:
    description: Closes rotten PRs after 7d of inactivity
    testgrid-create-test-group: "false"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240210-3c4f626498
      command:
      - commenter
      args:
      - |-
        --query=repo:gardener/ci-infra
        repo:gardener/gardener
        repo:gardener/gardener-extension-registry-cache
        repo:gardener/dependency-watchdog
        is:pr
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=168h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=The Gardener project currently lacks enough active contributors to adequately respond to all PRs.
        This bot triages PRs according to the following rules:
        - After 15d of inactivity, `lifecycle/stale` is applied
        - After 15d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 7d of inactivity since `lifecycle/rotten` was applied, the PR is closed
        
        You can:
        - Reopen this PR with `/reopen`
        - Mark this PR as fresh with `/remove-lifecycle rotten`

        /close
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token

- name: ci-gardener-triage-robot-pr-rotten
  interval: 1h
  cluster: gardener-prow-trusted
  decorate: true
  reporter_config:
    slack:
      channel: prow-alerts
  annotations:
    description: Adds lifecycle/rotten to stale PRs after 15d of inactivity
    testgrid-create-test-group: "false"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240210-3c4f626498
      command:
      - commenter
      args:
      - |-
        --query=repo:gardener/ci-infra
        repo:gardener/gardener
        repo:gardener/gardener-extension-registry-cache
        repo:gardener/dependency-watchdog
        is:pr
        -label:lifecycle/frozen
        label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=360h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=The Gardener project currently lacks enough active contributors to adequately respond to all PRs.
        This bot triages PRs according to the following rules:
        - After 15d of inactivity, `lifecycle/stale` is applied
        - After 15d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 7d of inactivity since `lifecycle/rotten` was applied, the PR is closed
        
        You can:
        - Mark this PR as fresh with `/remove-lifecycle rotten`
        - Close this PR with `/close`

        /lifecycle rotten
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token

- name: ci-gardener-triage-robot-pr-stale
  interval: 1h
  cluster: gardener-prow-trusted
  decorate: true
  reporter_config:
    slack:
      channel: prow-alerts
  annotations:
    description: Adds lifecycle/stale to PRs after 15d of inactivity
    testgrid-create-test-group: "false"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240210-3c4f626498
      command:
      - commenter
      args:
      - |-
        --query=repo:gardener/ci-infra
        repo:gardener/gardener
        repo:gardener/gardener-extension-registry-cache
        repo:gardener/dependency-watchdog
        is:pr
        -label:lifecycle/frozen
        -label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=360h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy.prow.svc.cluster.local
      - |-
        --comment=The Gardener project currently lacks enough active contributors to adequately respond to all PRs.
        This bot triages PRs according to the following rules:
        - After 15d of inactivity, `lifecycle/stale` is applied
        - After 15d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 7d of inactivity since `lifecycle/rotten` was applied, the PR is closed
        
        You can:
        - Mark this PR as fresh with `/remove-lifecycle stale`
        - Mark this PR as rotten with `/lifecycle rotten`
        - Close this PR with `/close`

        /lifecycle stale
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token
